### PR TITLE
[WIP] Sam tov docs updates

### LINKED ISSUE #424: Documentation: Coordinate Unwrapper code does not work
**Describe the bug**
Link: https://github.com/zincware/MDSuite/blob/293a96e549dbd142c879c18034b1db40b8932171/docs/source/tools.rst
The code in the documentation produces an error.

```python
import mdsuite as mds
NaCl = mds.Experiment(...)
```
 **Error Message**
   line 2, in <module>
    NaCl = mds.Experiment(...)
TypeError: __init__() missing 1 required positional argument: 'experiment_name'

### PR DESCRIPTION
**Pull request by SamTov**
Fix up docs to correctly display modules.

* closes #424

### CODE REVIEW

**Comment by SamTov** [comment]
Still finding the:

```bash
AttributeError: module 'tensorflow' has no attribute 'config'
```
error on compile in rtd.

This is resolved.

**Comment by PythonFZ** [comment]
> Still finding the:
> 
> ```shell
> AttributeError: module 'tensorflow' has no attribute 'config'
> ```
> 
> error on compile in rtd.

I could fix this one. But I don't know how to fix:

```
WARNING: autodoc: failed to import module 'setup'; the following exception was raised:
Traceback (most recent call last):
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tikhome/fzills/PycharmProjects/MDSuite/docs/../setup.py", line 29, in <module>
    with open("README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by SamTov** [comment]
> > Still finding the:
> > ```shell
> > AttributeError: module 'tensorflow' has no attribute 'config'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error on compile in rtd.
> 
> I could fix this one. But I don't know how to fix:
> 
> ```
> WARNING: autodoc: failed to import module 'setup'; the following exception was raised:
> Traceback (most recent call last):
>   File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
>     return importlib.import_module(modname)
>   File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/tikhome/fzills/PycharmProjects/MDSuite/docs/../setup.py", line 29, in <module>
>     with open("README.md", "r") as fh:
> FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
> ```

So all the docs that are live on this branch look good now. Do you get this error locally as well? 

Looks like the setup.py is being called from a different directory and so can't find the README. Using pathlib should resolve that.

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/MDSuite/MDSuite/docs/README.md'
```
So it appear to simply be looking in the docs folder for the path. I am not sure how to resolve this nicely. Need to think about it for a bit.

**Comment by SamTov** [comment]
So this actually does work on the hosted version if you go to https://mdsuite.readthedocs.io/en/samtov_docs_updates/modules_and_classes.html

**Comment by SamTov** [comment]
In this PR, all docs now render fine on readthedocs. There was some issue with the docs CI on GitHub that I will try to resolve. It works fine locally and on the RTD server so no reason it shouldn't work here...

**Pull request closed without merging**
