### PR TITLE
change load_matrix() return and signature

### LINKED ISSUE #445: load_matrix() should return a matrix
eperiment.load_matrix() has intricate logic to handle different arguments, but is only ever used to return a matrix of values for a single property of a single species. This could be simplified

### PR DESCRIPTION
**Pull request by christophlohrmann**
Fix #445 

I remember complaining about this before and the issue is not there anymore. What was the argument against this form?

### CODE REVIEW

**Comment by SamTov** [comment]
I discussed in the issue but the method here is legacy or was supposed to be removed. 

We discussed making a seperate data loading class for user to access data from the database. We wanted it to return a generator of the data from the database. This is seperate from the ones used in the internal calculators as they have memory management integrated into it.

**Comment by christophlohrmann** [comment]
would we need a big data loading class for the user?
Seems to me as the only thing that needs to change is database.load_data() to return a generator and not the full dataset.
experiment.load_data() is just a convenience-method to get the correct path to the correct file.

**Comment by SamTov** [comment]
So the database method is there to be called by the generators. So it can return as much data as it needs to and we use a wrapper for that to tell it how much to load. I like this as it means that the database can just return data and you manage the generator.

We can make an experiment.load_data() method which uses the database method to create a generator and that I think would be a great idea. Right now the database only return a dict as it is the most general method for the other methods. So the experiment method would have to re-format that and return a tensor of values.

**Comment by christophlohrmann** [comment]
I agree on separation of database and generator stuff. I will try to read through the code and understand how that works

**Comment by SamTov** [comment]
Awesome. The only methods are really in the data_manager. There are perhaps some legacy things laying around there as they weren't removed due to tests not being comprehensive enough. At this stage the data managers will always return a dictionary.

**Comment by SamTov** [comment]
@christophlohrmann Can this be closed?

**Pull request closed without merging**
