### PR TITLE
Add Tutorial 

### LINKED ISSUE #332: Add a tutorial data method.
**What feature would you like to see added?**
We could have a data loading method for the tutorials and CI built into MDSuite which just makes a temp directory, downloads some data and changes into the temp directory for further operations.

**Describe how this feature would improve the code**
It would make loading data really easy for our test cases and also fit nicely into the api.

**Describe how this feature would work/possible implementations**
Something like this currently exists in the green_kubo example found under MDSuite/examples/scripts

### PR DESCRIPTION
**Pull request by PythonFZ**
Fix #332

### CODE REVIEW

**Review by SamTov — COMMENTED** [review]
This is excellent however I think we could have it be more general if it were its own module which just handled downloading different sets of data in the ExampleData repo? What do you think?

**Comment by PythonFZ** [comment]
Maybe, but I don't know if would be worth writing a complex interface for a tutorial that will probably not be used by many. I think we should consider a tutorial situation where most if not all calculators and functions can be looked at and do not go beyond that.
If you have some ideas on how to make it look better, I will not argue against it.

**Comment by SamTov** [comment]
With the new DataHub and ZincHub repositories, loading data for examples is now quite simple and the need for this PR is gone. I would like to close it @PythonFZ.

**Comment by PythonFZ** [comment]
> With the new DataHub and ZincHub repositories, loading data for examples is now quite simple and the need for this PR is gone. I would like to close it @PythonFZ.

I also thinkt this should be closed and the examples provided will use ZnHub and make usinge example data sufficiently easy.

**Pull request closed without merging**
