### PR TITLE
Change compression algorithm

### PR DESCRIPTION
**Pull request by SamTov**
Found a case where the compression algorithm is too punishing. For scientific notation it is very easy to get values on a scale < 1e-6. Therefore I propose changing back to gzip where no data can be lost.

### CODE REVIEW

**Comment by christophlohrmann** [comment]
do we not use h5 and sql to store data? Where is that compression applied?

**Comment by PythonFZ** [comment]
Does this break backwards compatibility?

**Comment by SamTov** [comment]
> do we not use h5 and sql to store data? Where is that compression applied?

Compression is applied to the hdf5 datasets

**Comment by SamTov** [comment]
> Does this break backwards compatibility?
It shouldn't no.

**Comment by christophlohrmann** [comment]
> > do we not use h5 and sql to store data? Where is that compression applied?
> 
> Compression is applied to the hdf5 datasets

I thought hdf5 was a binary format.
Anyhow I think we should always go for lossless compression in any data storage

**Comment by SamTov** [comment]
> > > do we not use h5 and sql to store data? Where is that compression applied?
> > 
> > 
> > Compression is applied to the hdf5 datasets
> 
> I thought hdf5 was a binary format. Anyhow I think we should always go for lossless compression in any data storage

It is but you can still apply compression to it. I agree and have found some cases that really require it.

**Review by PythonFZ — APPROVED** [review]
Is it possible to test this? Otherwise I guess the tests fail because of something else?

**Comment by SamTov** [comment]
> Is it possible to test this? Otherwise I guess the tests fail because of something else?

So the tests failing in the IC could actually be because of the compression change but I need to check what is happening. In general it does not break backwards compatibility though because the compression algorithm is checked by h5py before loading the data. Otherwise one would need to pass the algorithm to the data loader.

I will try to resolve these tests failures locally.

**Review by PythonFZ — APPROVED** [review]

**Pull request merged**
