### PR TITLE
fixed single snapshot feature for lammps files

### LINKED ISSUE #379: Handle single snapshot trajectories
**What feature would you like to see added?**
For some computations we may want only a single snapshot eg. RDF, rings statistics (when implemented). 
Current reader gets the two first configurations to compute the sampling rate. 
Therefore, in the case of a single snapshot the code crashes. 

**Describe how this feature would work/possible implementations**
I have implemented it locally with a simple try/except block. 
However, I'd link this to the PR for the new file readers #372 since it makes more sense to do it in the new ones already.

### PR DESCRIPTION
**Pull request by Fratorhe**
Fix #379.
Current implementation gave a StopIteration exception when handling single snapshots. 

#### Summary of additions and changes

* Fixed using a try/except statement. 

I am developing a test case for graphs which use a single snapshot. 
It will be added soon, but I believe that it should be in another PR.

### CODE REVIEW

**Comment by christophlohrmann** [comment]
Looks good to me @PythonFZ do you know what is going on in CI?

**Comment by PythonFZ** [comment]
> Looks good to me @PythonFZ do you know what is going on in CI?

Not really tbh

**Comment by christophlohrmann** [comment]
maybe rerunning will solve it :)

**Comment by SamTov** [comment]
> maybe rerunning will solve it :)

Had the same idea

**Comment by SamTov** [comment]
```bash
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```
This one issue but I don't think it is the same for all of them.

**Comment by SamTov** [comment]
One error was this request thing, not too sure what it is or how it came up, the other was the batching, I guess the restructure of the calculators needs to happen so that the new database structure can be applied and batching redone as it seems that there are a lot of hard to reproduce bugs that plague it.

**Review by christophlohrmann — APPROVED** [review]

**Pull request merged**
