### PR TITLE
Update CI to use Python 3.10

### PR DESCRIPTION
**Pull request by PythonFZ**
Run tests on Python 3.10

### CODE REVIEW

**Comment by SamTov** [comment]
Open3D does not yet support python 3.10 and so the dev-requirements are uninstallable. 

Monitor https://github.com/isl-org/Open3D/issues/4535

Essentially they are waiting for PyTorch to support 3.10 and then they will too.

**Comment by PythonFZ** [comment]
@SamTov  having a `wontfix` badge here could give the false impression that we never want to support Python>=3.9.

**Comment by SamTov** [comment]
With https://github.com/isl-org/Open3D/pull/5320 this should be fine soon. The wheels are out but they are waiting on the next stable release for the default. At this point we can trigger this PR again.

**Review by SamTov — APPROVED** [review]
Nice addition, as soon as the tests pass it is good to go.

**Pull request merged**
